a = int(input('Entre com o primeiro valor:'))
b = int(input('Entre com o segundo valor:'))
soma = a + b
subtracao = a - b
multiplicacao = a * b
divisao = a / b
resto = a % b
print (f'soma = {soma};'
        f'\nsubtração = {subtracao};'
        f'\nmultiplicação = {multiplicacao};'
        f'\ndivisão = {divisao};'
        f'\nresto = {resto};')
